project:
    type: book

book:
    title: "Explainable Machine Learning: A Tutorial"
    author: "Jane Doe"
    date: "7/10/2026"

    sidebar:
        collapse-level: 1

    chapters:
        - index.qmd
        - part: 1-basics/1-0-intro.qmd
          chapters:
              - 1-basics/1-1-categorization.qmd
              - 1-basics/1-2-feature-attribution.qmd
              - 1-basics/1-3-concept-bottleneck-methods.qmd
              - 1-basics/1-4-practical-considerations.qmd
        - part: 2-xllms/2-0-intro.qmd
          chapters:
              - 2-xllms/2-1-activation-based-explanations.qmd
              - 2-xllms/2-2-concept-based-explainability.qmd
              - 2-xllms/2-3-concept-discovery.qmd
              - 2-xllms/2-4-mechanistic-interpretability.qmd
              - 2-xllms/2-5-attention-visualization-methods.qmd
        - part: 3-xrl/3-0-intro.qmd
          chapters:
              - 3-xrl/3-1-foundations.qmd
              - 3-xrl/3-2-taxonomy.qmd
              - 3-xrl/3-3-visualization-based-approaches.qmd
              - 3-xrl/3-4-policy-extraction-and-decision-trees.qmd
        - part: 4-xmas/4-0-intro.qmd
          chapters:
              - 4-xmas/4-1-foundations.qmd
              - 4-xmas/4-2-taxonomy.qmd
              - 4-xmas/4-3-technical-approaches-and-methodologies.qmd
              - 4-xmas/4-4-applications.qmd
              - 4-xmas/4-5-evaluation-metrics.qmd
              - 4-xmas/4-6-key-challenges-and-open-research-directions.qmd
        - references.qmd

bibliography: references.bib

format:
    html:
        theme:
            - lumen
        code-fold: true
    pdf:
        documentclass: scrreprt
