# More stuff to sort in

Decision trees are inherently interpretable. Once a policy is learned, the reasoning behind every decision can be clearly traced by following the tree's decision nodes. This works well when individual state features are meaningful (e.g., position, velocity); however, it struggles with high-dimensional state spaces such as raw pixels

Example: VIPER @bastani2018verifiable, an approach to make RL verifiable by learning decision tree policies


\section{Representation space analysis}

Just like in supervised learning, it is of great interest to understand what kind of internal representations deep networks actually discover. High-dimensional state spaces such as pixels can be mapped to lower-level features using t-SNE.

\section{Explaining decisions through critical states}

Example: StateMask \cite{cheng2023statemask}

\section{Trajectory-based methods}

An example of behavior discovery and attribution is this: \cite{rishavbehaviour}

\section{Explainability via counterfactual reasoning}

A recent focus in the RL community is using world models for better sample-efficiency and higher performance. By having a world model learn the environment dynamics $P(s_{t+1}\mid s_t,a_t)$, we can predict future states without interaction with the real environment. This is essential for planning and also has the useful side effect that it enables counterfactual reasoning, useful for generating "what-if" scenarios.

\cite{van2018contrastive} is among the first to use world models for counterfactual explanations in RL.

\cite{singh2025explainable} uses backward counterfactuals ("What state would cause agent to do $X$?"), using a reverse world model $P(s_t\mid s_{t+1},a_t)$

\section{Evaluation of XRL methods}

Unique challenges to XRL are the sequential nature of decisions, requiring understanding of strategies rather than single model predictions, temporal dependencies making explanations more complex, and evolving agent behavior during learning.

There are three evaluation levels identified  by \cite{doshi2017towards}, which are increasingly specific and costly: functionally grounded (computational metrics only), human-grounded (general users + simplified tasks), and application-grounded (domain experts + real tasks).

\section{Applications}
