# Pertubation-Based Saliency Maps

Key Paper: @greydanus2018visualizing
- Sources: [Paper](https://arxiv.org/abs/1711.00138) and [code](https://github.com/greydanus/visualize_atari)
- Method authors: Sam Greydanus, Anurag Koul, Jonathan Dodge, Alan Fern

::: {.callout-tip title="TL;DR"}
**Pertubation-based saliency maps** are useful to visualize attention of an RL agent in a visual environment.
:::

## Introduction

@greydanus2018visualizing use saliency maps to visualize RL policies in pixel-based environments (Atari).

In particular, they use a pertubation-based approach, witih the leading question: "How much does removing information from the region around location (i, j) change the policy?"


## Method: Pertubation-based saliency maps

Given an original image $I_t$

$I_{1:t}$ is a sequence of images.

Hadamard product $\odot$

$$\Phi(I_t,i,j)=\underbrace{I_t}_{\text{image frame}}\odot (1-\underbrace{M(i,j)}_{\text{mask}})+\underbrace{A(I_t,\sigma_A)}_{\text{blurred frame}}\odot M(i,j)$$


This visualization technique is separate from the RL algorithm used for training. The authors used the A3C algorithm, which yields both a policy and value function. The above procedure for constructing pertubation-based saliency was applied to both the policy  $\pi$ and $V^\pi$


They use patches of 5x5 pixels.

## Tradeoffs

::: {layout-ncol="2"}

| Pros |
| :--- |
| Fast development |
| High community support |

| Cons |
| :--- |
| Steep learning curve |
| Hard to debug |

:::

## Related

- Instead of pertubation-based saliency maps, prior work has used Jacobian-based ones {@wang2016dueling, @zahavy2016graying}.
